# Generated by Django 2.2.7 on 2019-11-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('teamCount', models.PositiveIntegerField()),
                ('membersPerTeam', models.PositiveIntegerField()),
                ('typeOfContest', models.PositiveIntegerField(default=0)),
                ('numberOfRounds', models.PositiveIntegerField(default=1)),
                ('numberOfSeries', models.PositiveIntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('canVote', models.BooleanField(default=False)),
                ('isStarted', models.BooleanField(default=False)),
                ('currentRound', models.PositiveIntegerField(default=1)),
                ('currentSeries', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=40)),
                ('numberOnBack', models.PositiveIntegerField()),
                ('isDisqualified', models.BooleanField(default=False)),
                ('isStillCompeting', models.BooleanField(default=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='contestapp.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('seriesNumber', models.PositiveIntegerField(default=1)),
                ('isStarted', models.BooleanField(default=False)),
                ('hasEnded', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='contestapp.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officialSurname', models.CharField(max_length=25)),
                ('officialName', models.CharField(max_length=25)),
                ('stageName', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='contestapp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('percent', models.PositiveIntegerField(default=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='contestapp.Contest')),
            ],
        ),
    ]
