# Generated by Django 2.2.7 on 2019-11-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='numberOfSeries',
        ),
    ]
