# Generated by Django 2.2.7 on 2019-11-19 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0003_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='postedBy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
