# Generated by Django 2.2.7 on 2019-11-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0004_auto_20191119_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
