# Generated by Django 2.2.7 on 2019-12-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0005_auto_20191119_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='percent',
            field=models.PositiveIntegerField(),
        ),
    ]
